# Generated by Django 3.2.7 on 2021-09-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, default='profiles/default-profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
